Refactored code and improvements with errors
rubengomez/mints-ruby-sdk pull request #44
Opened 2023-02-27 20:03 UTC by fabianmints

2023-03-08 21:38 UTC, superchairon commented on lib/client.rb
> +            detail = response&.response&.message || 'Unknown error'
Si esta bien que el response.message.message vaya tanto en el titulo como en el detail?

2023-03-08 21:44 UTC, superchairon commented on lib/mints/helpers/proxy_controllers_methods.rb
> +  def url_need_cache?(full_url)
Agergar comentarios a estas funciones

2023-03-08 21:55 UTC, fabianmints commented on lib/mints_helper.rb
>      def get_query_results(url, options = nil, use_post = true)
Jaja ese esta así desde el inicio, y por el momento no lo moví, lo cambio

2023-03-08 21:55 UTC, fabianmints commented on lib/mints/helpers/proxy_controllers_methods.rb
> +  def url_need_cache?(full_url)
Va

2023-03-08 21:56 UTC, fabianmints commented on lib/client.rb
> +            detail = response&.response&.message || 'Unknown error'
En su momento lo deje así, pero creo que sería mejor quitar el response.message.message del title, tu que opinas?

2023-03-08 22:48 UTC, superchairon commented on lib/client.rb
> +            detail = response&.response&.message || 'Unknown error'
Pues creo que da igual, solo queria saber si era intencinonal o no.

2023-03-09 20:51 UTC, superchairon approved these changes

2023-03-17 15:28 UTC, rubengomez requested changes

2023-03-17 15:28 UTC, rubengomez commented on lib/mints/controllers/concerns/mints_clients.rb
> +    contact_token_id = cookies[:mints_contact_id]
Estandarizar nombres de variables y el scope que tienen, en la funcion `set_mints_pub_client` la variable se llama `contact_token` y es una variable de clase.

2023-03-17 15:28 UTC, rubengomez commented on lib/client.rb
>              options[:jfilters] = Base64.encode64(JSON.generate(options[:jfilters]))
Podemos aprovechar para agregar `afilters` y `rfilters`, podrian estar en un array los 3 e iterar sobre ellos para aplicarles el encode

2023-03-17 15:28 UTC, rubengomez commented on lib/client.rb
> +        raise 'NoActionError' unless %w[get create post update put delete destroy].include?(action)
Faltó agregar la función `verify_response_status` al metodo `method_missing`

2023-03-17 15:28 UTC, rubengomez commented on lib/mints/controllers/base_api_controller.rb
> +    include MintsClients
Se dejan disponibles todos los clientes en el base api controller?

2023-03-17 15:28 UTC, rubengomez commented on lib/mints/controllers/base_controller.rb
> +    include MintsClients
Creo que si lo dejamos asi vamos a promover el uso del API de User en vistas públicas.

2023-03-17 15:28 UTC, rubengomez commented on lib/mints/controllers/base_controller.rb
> +    include MintsClients
Preferiría que estuvieran separados, include PubClient, include ContactClient, include UserClient, y nosostros dejar por defecto los recomendados, y si hay alguna excepción donde se ocupe uno de los no recomendados entonces se hace el include en el controlador que hereda de este.

2023-03-17 15:42 UTC, fabianmints commented on lib/mints/controllers/concerns/mints_clients.rb
> +    contact_token_id = cookies[:mints_contact_id]
Va, de una vez estandarizo ello

2023-03-17 15:49 UTC, fabianmints commented on lib/client.rb
>              options[:jfilters] = Base64.encode64(JSON.generate(options[:jfilters]))
Va, los agrego de una vez, el de rfilters es el único que lo transformábamos de forma diferente, ahí veo que onda

2023-03-17 15:50 UTC, fabianmints commented on lib/client.rb
> +        raise 'NoActionError' unless %w[get create post update put delete destroy].include?(action)
Va, lo agrego

2023-03-17 15:53 UTC, fabianmints commented on lib/mints/controllers/base_controller.rb
> +    include MintsClients
Pues a final de cuentas se maneja de una forma similar ahorita, solo que si se quiere agregar el de User, seria sobrescribir el método, de esa forma lo que si falto es no promover el api de user

2023-03-17 17:54 UTC, rubengomez approved these changes

2023-03-17 17:54 UTC, merged